Add missing DGL_NAMESPACE qualifier
Fixes a build failure on MSVC:

    distrho\src\DistrhoUIInternal.hpp(270,39): error C2061: syntax error: identifier 'IdleCallback'
      (compiling source file 'distrho/DistrhoPluginMain.cpp')